import pyautogui, mouseinfo, time 

pyautogui.press('win')
pyautogui.write('chrome')
pyautogui.moveTo(686,494, duration=1)
pyautogui.click()

pyautogui.moveTo(1050,80, duration=1)
pyautogui.click()
pyautogui.write('https://www.devocionaldiario.com.br/')
pyautogui.press('enter')
pyautogui.moveTo(1509,293, duration=0.5)
time.sleep(3)
pyautogui.scroll(-500)

pyautogui.moveTo(552,512, duration=1)
time.sleep(1.5)
pyautogui.mouseDown()
pyautogui.moveTo(707,584, duration=1)
time.sleep(0.5)
pyautogui.mouseUp()
time.sleep(0.5)
pyautogui.hotkey('ctrl', 'c')
time.sleep(0.5)

pyautogui.hotkey('ctrl', 't')
pyautogui.write("https://www.oratlas.com/leitor-de-texto-online")
pyautogui.press('enter')
time.sleep(3)
pyautogui.moveTo(725,363, duration=0.5)
pyautogui.click()
time.sleep(0.5)
pyautogui.hotkey('ctrl', 'v')
time.sleep(0.5)
pyautogui.moveTo(1054,256, duration=0.5)
pyautogui.click()
mouseinfo.mouseInfo()
